name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: gh640/command-result-action@v1
        id: cra
        with:
          command: pwd
      - run: |
          {
            echo '### outputs'
            echo ''
            echo '`exitCode`:'
            echo ''
            echo '```'
            echo "${CRA_EXIT_CODE}"
            echo '```'
            echo ''
            echo '`stdout`:'
            echo ''
            echo '```'
            echo "${CRA_STDOUT}"
            echo '```'
            echo ''
            echo '`stderr`:'
            echo ''
            echo '```'
            echo "${CRA_STDERR}"
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
        env:
          CRA_EXIT_CODE: ${{ steps.cra.outputs.exitCode }}
          CRA_STDOUT: ${{ steps.cra.outputs.stdout }}
          CRA_STDERR: ${{ steps.cra.outputs.stderr }}
